### ISSUE TITLE
2nd Plan by park-sohyeon

### ISSUE THREAD

**Issue by park-sohyeon** [su-hyeok/c_algorithm#10]
### 3장

1/11 - 3시간
1/12- 2시간
1/13- 2시간
1/14- 2시간
1/15- 2시간

**Comment by park-sohyeon** [comment]
1장 -  기본 알고리즘(최댓값 구하기, 합 구하기, 다중 루프, 직각 이등변 삼각형)
2장 - 배열(요소 개수값,void 포인터, 난수 사용)
3장 부터는 굳이 모든 문제를 코딩하지 않고 알고리즘이 이해되는 것은 바로바로 넘어감.
3장 - 선형검색, bsearch함수
4장 - 스택과 큐 (푸쉬, 스택과 큐 다양한 함수 사용해 프로그램 이해 )
5장 - 재귀(하노이 탑, 8퀸 이해하기)
6장 - 정렬/ 버전 1만 실행 (버블 정렬, 단순 선택, 단순삽입, 셸, 퀵)- 연습문제 다 풀지 않고 이해앞 풀이랑 비슷한 것 넘기기.
7장 - 배열로 집합 만들기 - 연습문제 1번(여기까지 완료), 비트벡터 - 연습문제 2번
8장 - (완료)

**Comment by jongfeel** [comment]
현재 6장 완료고, 이번주가 설 연휴인데 7장 완료가 목표인것 까지는 알겠습니다.
하지만, 계획했던 2월 중에 어디까지 할 지를 정해보셨으면 좋겠습니다.

무모한 계획과 일정으로 목표를 달성하지 못하면
남는건 자기 반성과 변명뿐입니다.

**Comment by park-sohyeon** [comment]
네엡!! 일주일에 한 챕터를 끝내는 식으로 진행하고
2월 둘째주 - 7장,8장 1/2
셋째주 - 8장 나머지, 9장 1/2
넷째주 - 9장 나머지,10장
남은 11장은 개인적으로 3월 첫째주까지 진행할 예정입니다!!
