### ISSUE TITLE
vscode 헤더파일 관련질문입니다

### ISSUE THREAD

**Issue by su-hyeok** [su-hyeok/c_algorithm#11]
말글대로 vscode에서 헤더파일을 어떻게 추가해야하는 건지 잘 모르겠습니다
.h 파일을 만들고 .c 파일을 만들고 이 둘을 main코드에서 활용하려하는데 그게 안됩니다. 
소스코드는 problem/su-hyeok/develop 브렌치에서 Q4-1.c , IntStack.c , IntStack.h입니다.

**Comment by jongfeel** [comment]
어떻게 안되는지 알려줄 수 있을까요?

**Comment by su-hyeok** [comment]
Q4-1을 실행하였을때 각각의 함수들 즉, push, pop등으로 만들어 놓은 함수들이 정의되어있지 않다고 나옵니다

**Comment by jongfeel** [comment]
How is the build CLI?
Did you compile include IntStack.h and IntStack.c files?

**Comment by su-hyeok** [comment]
그 세개 파일을 동시에 컴파일했지만 안됩니당..

**Comment by jongfeel** [comment]
컴파일 한 명령어가 어떻게 될까요?

그리고 오류 메시지가 어떻게 나오나요?

**Comment by jongfeel** [comment]
@zsueue 님은 같은 문제를 어떻게 풀었는지 공유해 주실 수 있을까요?

**Comment by parkwltn** [comment]
4-1.cpp, IntStack.h, IntStack.cpp 파일 생성 후 
4-1.cpp, IntStack.cpp에 include "IntStack.h" 하고 실행했습니다. (@su-hyeok 동일)

방금 @su-hyeok 파일 실행해봤는데 search 함수에서 괄호 개수가 안 맞아서 } 추가했더니 실행됩니다.

#### 수정한 부분
IntStack.c 파일
- int search(const IntStack* s, int x)
} 추가
- void Print(const IntStack * s), void terminate(IntStack * s)
tap 이동

**Comment by jongfeel** [comment]
@zsueue 님의 Visual Studio build CLI를 확인하고 그 CLI를 남겨 놓으면 그 옵션대로 vscode에 적용해서 실행되는지 확인

**Comment by su-hyeok** [comment]
커맨드 라인을 어떻게 찾아볼수 있을까요

**Comment by jongfeel** [comment]
### Visual Studio Build CLI

Walkthrough: Using MSBuild to Create a Visual C++ Project
https://docs.microsoft.com/en-us/cpp/build/walkthrough-using-msbuild-to-create-a-visual-cpp-project?view=msvc-160

제목이 이렇게 되어 있는데 Visual Studio의 경우에는 msbuild.exe라는 툴을 사용합니다.
msbuild,exe는 cl.exe라는 컴파일러와 link.exe라는 링커로 프로그램의 exe 파일을 생성하기 때문에
gcc.exe와는 다른 구조의 build cli를 가지고 있습니다.

실제 hello world 프로젝트를 그냥 cli로 해보면 아래와 같은 스크린샷 처럼 나옵니다.
![image](https://user-images.githubusercontent.com/17442457/104876320-cdf2a900-599a-11eb-9fb4-cbf9dbc9d078.png)


**중요한건 Visual Studio는 gcc를 쓰지 않으므로 CLI 호환이 불가능**하다는 점이죠.

Visual Studio를 쓰시는 분은 참고만 하시면 됩니다.

**Comment by jongfeel** [comment]
@su-hyeok 

task.json에 힌트가 있습니다.

https://github.com/su-hyeok/c_algorithm/blob/7bee0704cba9538ae4690031ad36fc5879cdb178/.vscode/tasks.json#L6-L12

지금은 단독 파일 하나만 (${file}) 컴파일을 하고 실행 파일을 생성하기 때문에
이 task.json 파일로는 제대로 빌드가 되지 않습니다.

힌트는 파일이 아닌 폴더를 선택하는 옵션을 지정하고 그 폴더 안에 모든 .h 및 .c 파일을 넣고 빌드해 보면 될 가능성이 있습니다.
