### ISSUE TITLE
Recommended to use pull request

### ISSUE THREAD

**Issue by jongfeel** [su-hyeok/c_algorithm#12]
#11 의 이슈에 대해서 답변을 잘 해주셨는데요

코드 수정을 하고 확인해야 하는 작업은 사실 pull request를 사용하는게 효과적입니다.

다음에 한번 해보면 어떨까 싶고요.

어떻게 하는 건지 잘 모르겠다 싶으시면 제가 한번 보여드릴 수도 있습니다.

@su-hyeok , @park-sohyeon 
다른 분들도 참고하셨다가 필요할 때 해보시면 좋겠습니다.

**Comment by parkwltn** [comment]
네! 다음에 코드 수정할 상황이 생기면 Pull Request 해보겠습니다!
