### ISSUE TITLE
2nd online meeting

### ISSUE THREAD

**Issue by park-sohyeon** [su-hyeok/c_algorithm#16]
계획 되었던 내일 미팅을 팀원들과 상의한 결과 다음주에 진행하는 것으로 결정하였습니다.
다음주 금요일에 11시 가능할까요??

**Comment by jongfeel** [comment]
네 알겠습니다.

다음주에 물어볼 부분이 있으면 issue에 올려 주시고
남아 있는 issue 중에 추가 코멘트나 피드백을 남겨야 하는 부분은 추가하고 close 해 주세요.
