### ISSUE TITLE
2nd online meeting

### ISSUE THREAD

**Issue by park-sohyeon** [su-hyeok/c_algorithm#18]
팀원들의 개인적 질문이 없고, 개인적인 시험 준비 등으로 목표로 했던 진도를 다 채우지 못해 팀원들과 상의 후 미팅을 다음주에 진행하는 것으로 결정하였습니다.
다음주 금요일에 11시 가능할까요??

**Comment by jongfeel** [comment]
다음주로 해도 됩니다. 일정은 변경할께요.

목표했던 진행률이 어느 정도 되고
일정대로 달성 가능한지 체크해 보는 것도 좋을 것 같습니다.

github의 commit log가 증명하듯이 박지수님이 좀 꾸준하게 하고 있고
다른 분들은 하는지 안하는지 잘 모르겠어요.

여러분들이 프로그래밍 익히려고 시작한 거니까요
스스로를 속이지 않고 계속 할 수 있으면 좋겠습니다.

**Comment by su-hyeok** [comment]
넵!!

**Comment by park-sohyeon** [comment]
넵 알겠습니다!!

**Comment by jongfeel** [comment]
오늘이 미팅 날인데요.
몇 가지를 얘기해 보려고 합니다.

### No request to me

이번주 역시 저에게 요청하신 부분이 없고 조용히 commit 하면서 문제 풀고 계신거 같아서
미팅은 다다음주인 2월 19일에 진행하겠습니다.

### Feedback

진행률과 일정대로 달성 가능여부에 체크해 보라고 했는데
체크 하신건지 잘 모르겠습니다.


맨 처음 저한테 메일 보낼 때를 잘 기억해 보시면
여러분들 끼리 책보고 공부하는데 멘토가 필요 없을 수도 있다고 했었습니다.
거기에 여러분들은 부족한 부분에 대해 도움을 요청했었고 저는 리뷰를 통해 도와줄 수 있다고 했었죠.

지금 진행하고 있는 상황이 제가 필요한 상황인지도 다시 한번 생각해 보셨으면 좋겠습니다.

**Comment by park-sohyeon** [comment]
아 넵!! 그동안의 진행률, 달성여부를 이슈에 정리해 올리겠습니다!!
