### ISSUE TITLE
kmp 알고리즘 테이블 생성 시 중간에서 일치하지 않은 경우 skip 테이블을 참조하여 pp값을 변경시키는 이유

### ISSUE THREAD

**Issue by parkwltn** [su-hyeok/c_algorithm#21]
교재에 나와 있는 kmp 알고리즘 코드를 보고 있는데요.
skip table을 만드는 과정에서 이해가 되지 않는 부분이 있어 질문드립니다.
```
int kmp_match(const char txt[], const char pat[])
{
	int pt = 1;		/* txt 커서 */
	int pp = 0;		/* pat 커서 */
	int skip[1024]; /* skip table */

	/* skip table 만들기 */
	skip[pt] = 0; //table : | - | 0 | 
	while (pat[pt] != '\0') { 
		if (pat[pt] == pat[pp]) //겹친 패턴의 문자가 일치하면
			skip[++pt] = ++pp;  //table : | - | 0 | 1 |
		else if (pp == 0) //
			skip[++pt] = pp; //table : | - | 0 | 0 |
		else 
			pp = skip[pp]; //pp == skip[0]
	}
}
```
skip table 을 만드는 코드입니다.
여기서 
```
else 
	pp = skip[pp]; 
```
패턴의 중간에서 불일치할 경우, skip 테이블을 참조하여 pp 값을 변경시키는 이유가 궁금합니다.

전체 코드는 zsueue/exercise 브랜치의 Ch8/kmp_match.cpp 입니다.
PR을 해봤는데 kmp_match.cpp 외에도 나머지 커밋들이 다 PR 돼버려서... 일단 close 했습니다.

**Comment by jongfeel** [comment]
pull request를 할 다른 branch를 생성해서 리뷰할 파일만 commit 해서 올리면 잘 될겁니다.
merge할 branch는 zsueue/exercise 겠죠?

**Comment by parkwltn** [comment]
zsueue/kmp_match branch 생성해서 kmp_match.cpp commit 하고 zsueue/exercise로 merge 했습니다! 감사합니다.

**Comment by jongfeel** [comment]
#22  아직 merge는 안한 상태입니다.

이 pull request에 issue에 적은 내용을 다시 적어주시면 좋을 것 같고요.
reviewer로 절 할당해 주시면 됩니다.

**Comment by parkwltn** [comment]
내용 추가하고, reviewer 할당하고, merge 했습니다.

**Comment by jongfeel** [comment]
zsueue/exercise branch를 다시 pull 하시면 원래대로 돌아와 있을 겁니다.

번거로우시겠지만 다시 pull request를 요청하시고
이번에는 테스트 했던 파일과 패턴 문자열을 알려주시면 좋을 것 같아요.

그리고 pull request를 요청 하신 후에는 reviewer만 지정해 주시고
리뷰가 이루어지고 난 이후에 merge를 하셔서 merge 하셨으면 좋겠습니다.

**Comment by parkwltn** [comment]
pull 하고 다시 PR을 요청하려고 하는데요...

> 테스트 했던 파일과 패턴 문자열을 알려주시면 좋을 것 같아요.

테스트 했던 파일이 무엇인지 모르겠습니다. 
텍스트 문자열을 말씀하시는 건가요? 아니면 이런 파일들을 말씀하시는 건가요?
<img width="478" alt="1" src="https://user-images.githubusercontent.com/67677312/107874474-48acd680-6efd-11eb-9690-34fb81414e45.PNG">
<img width="491" alt="2" src="https://user-images.githubusercontent.com/67677312/107874476-49de0380-6efd-11eb-922b-58dcf8a778ad.PNG"> 

> 그리고 pull request를 요청 하신 후에는 reviewer만 지정해 주시고
리뷰가 이루어지고 난 이후에 merge를 하셔서 merge 하셨으면 좋겠습니다.

이 부분은 이해했습니다! 감사합니다.

**Comment by jongfeel** [comment]
아 제가 txt라고 해서요 txt 파일에 있는 내용을 복사해서 붙여 넣는건 줄 알았는데
텍스트 문자열이라고 하신 거 보니 직접 입력하신 건가 보군요.

그러면
텍스트 문자열과 패턴 문자열이 뭔지 알려주시면 좋을 것 같아요.

**Comment by parkwltn** [comment]
테스트 했던
텍스트 문자열은 ZABCABEABCABDAE
패턴 문자열은 ABCABD 입니다. 

reviewer 지정하고, PR 요청했습니다.

**Comment by parkwltn** [comment]
# [해결!](https://github.com/su-hyeok/c_algorithm/pull/24)
