### ISSUE TITLE
3rd online meeting

### ISSUE THREAD

**Issue by jongfeel** [su-hyeok/c_algorithm#25]
좀 늦은 감이 있지만 진행 여부를 결정했으면 좋겠는데요.

이걸 결정해야 하는 이유는 아래 두 가지 입니다.

- 논의 내용을 지수님만 올려서 나머지 두 분이 참여하는게 의미가 있는지 판단
- 지수님의 논의 내용을 얘기하는데 드는 시간이 짧을 것 같다는 저의 소견

그래도 온라인 미팅으로 얘기하고 싶다면 해도 됩니다.
아니라고 생각하시면 코멘트 달아 주세요.

**Comment by parkwltn** [comment]
저는 짧더라도 온라인 미팅을 진행했으면 합니다.
계획했던 종료일이 일주일 정도 남았기도 하고, 가능하다면 이번 온라인 미팅을 통해 약 7주간의 활동에 대해  전반적인 피드백을 듣고 싶습니다.

**Comment by jongfeel** [comment]
네 좋습니다

**Comment by jongfeel** [comment]
내용 간략 정리

- #24 kmp 알고리즘에 skip table 내용 간략 리뷰
- 프로그래밍에서 중요한 부분을 차지하는 디버깅(debugging)에 대한 의미 -> 진짜 벌레 퇴치!
- 알고리즘 문제 푸는 것과 한이음 프로젝트를 진행할 때의 개발은 다른 느낌이기 때문에 경험해 보고 적성을 찾아봐도 좋음
