### ISSUE TITLE
멘토링 중단에 관하여...

### ISSUE THREAD

**Issue by parkwltn** [su-hyeok/c_algorithm#27]
소현이와 상의를 했는데요. 계획했던 종료일보다 일주일 먼저 중단했으면 합니다...
개인적인 일이지만 다음 주에 자격증 시험을 앞두고 있는데 병행이 어려울 것 같아서 자격증에만 집중하고자 합니다.
#9, #10 에서 계획했던 분량을 거의 하지 못해 아쉽지만, [남은 부분](https://github.com/su-hyeok/c_algorithm/issues/26)은 따로 정리를 해두었고 여유가 될 때 개인적으로 공부할 예정입니다.
두 달 동안 신경써주셔서 감사합니다!

**Comment by jongfeel** [comment]
자격증 시험 준비까지 하고 계셨군요.

처음에 목표했던 분량을 완료하지 못했지만, 어쨌든 계획적으로 진행했고 그 계획의 목표를 달성한 만큼만이라도 여러분들이 잘 해낸거라 생각해 주시면 좋겠습니다. 남은 부분도 나중에 따로 하신다고 하면 꼭 계획을 세우시고 하셨으면 좋겠습니다.

수고 많으셨어요. 감사합니다.

**Comment by parkwltn** [comment]
짧은 시간이었지만 목표를 세우고 계획대로 달성하고, 그래도 마지막에 디버깅을 통한 문제 해결도 해보고 ㅎㅎ 좋은 경험이었습니다. 기회가 된다면 다음에 더 좋은 모습으로 만나뵈었으면 좋겠습니다. 감사합니다~

**Comment by park-sohyeon** [comment]
저도 방학동안 계획을 세워 알고리즘을 공부할 수 있어서 좋았습니다!! 문제 풀이라 질문이 많이 없었지만 다음에 또 기회가 된다면 또 뵈었으면 좋겠습니다. 감사합니다!!
