### ISSUE TITLE
질문입니다

### ISSUE THREAD

**Issue by su-hyeok** [su-hyeok/c_algorithm#4]
vscode에서 scanf를 사용하고싶은데 오류가 나지는 않는데 실행결과가 안나옵니다 예를들어
int main(){
    int n;
    printf("숫자를 입력하세요: ");
    scanf("%d",&n);
    printf("값은 %d 입니다.\n",n+1);

} 이런식으로 코드를 짜면 실행 화면에 
숫자를 입력하세요 :  <=이 화면이 나오고 사용자가 숫자를 입력하면
값은 n+1입니다 이런식으로 떠야하는데 
숫자를 입력하라는 화면부터 안나옵니다 혹시 어떻게 해결을 해야 할까요

vscode에서 c 언어를 컴파일 하기위해 MinGW를 설치하고 환경변수에 시스템변수의 Path 에서 C:\MinGW\bin 이렇게 설정해주었습니다. 
결과적으로 이상황에서 scanf를 vscode에서 사용하려면 어떠한것을 해줘야하는지 궁금합니다

**Comment by jongfeel** [comment]
세팅 했던 vscode 작업 폴더를 올려주시면 어떨까요?

**Comment by su-hyeok** [comment]
problem/su-hyeok/Develop branch에 있는 Q6.c 파일입니다!

**Comment by zsueue** [comment]
scanf_s로 하면 실행됩니당

**Comment by jongfeel** [comment]
요 파일인거 같은데
오류 메시지가 어떻게 나오던가요?

https://github.com/su-hyeok/c_algorithm/blob/18d329601fdb3a8d003d3f4a7d221c2655cf803b/Q6.c#L19-L25

**Comment by su-hyeok** [comment]
네 오류메시지가 나오지 않습니다 다만 사용자가 숫자를 입력해야하지만 숫자를 입력하세요: 라는 문구도 나오지를 않습니다

**Comment by su-hyeok** [comment]
아 이문제는 해결 됐습니다

**Comment by jongfeel** [comment]
어떻게 해결했는지 내용을 알려줄 수 있을까요?

**Comment by su-hyeok** [comment]
vscode 설정에서 run in terminal 로 설정후에 실행시키니 되었습니다

**Comment by jongfeel** [comment]
그런데 vscode 안에서 터미널로 실행시키는 거니
사실상 vscode가 아니어도 그냥 터미널 창에서 정상적으로 실행이 되는 코드는 맞죠.

> vscode에서 c 언어를 컴파일 하기위해 MinGW를 설치하고 환경변수에 시스템변수의 Path 에서 C:\MinGW\bin 이렇게 설정해주었습니다.
결과적으로 이상황에서 scanf를 vscode에서 사용하려면 어떠한것을 해줘야하는지 궁금합니다

그런데 이렇게 질문하신 건 터미널이 아니라 vscode 세팅을 올바르게 해서
vscode 메뉴에 Run > Start Debugging 으로 실행 시키고 싶었던거 아닌가요?
