### ISSUE TITLE
question9, int set-up

### ISSUE THREAD

**Issue by park-sohyeon** [su-hyeok/c_algorithm#5]
연습문제 9번을 풀던 도중
int main(void)에서 int 설정을 int a,b; 로 해주었습니다. 그 이유는 int sumof(int a,int b)에 있는 a,b를 사용하기 위해서인데,
정답에는 sum도 int 설정을 해줍니다. 

정답에는 변수 i, a,b,sum 중 int main(void)에서 int 설정을 int a,b, sum; 으로 해주는데 왜 i는 안해주나요?
그리고 왜 sum도  int main(void)에서 int 설정을 해주나요?

디버깅은 변수 설정이 달라져도 다 답이 나옵니다.

파일은 park-sohyeon/exercise 에서 Q9 입니다.

**Comment by jongfeel** [comment]
질문이 잘 이해가 가지 않는데요.

차근 차근 짚어 보면 좋을 것 같습니다.

https://github.com/su-hyeok/c_algorithm/blob/07076de9a0d2b7c833e91d86e850a8c8e82ee065/Q9.cpp#L24-L33

여기서 a와 b의 변수 type이 int 입니다.

i 변수와 sum 변수는 보이지 않는데 int type을 어디에 선언했나요?

**Comment by park-sohyeon** [comment]
i와 sum은 void sumof(int a, int b) 함수에서 int a,b, i, sum 을 해주었습니다!!

**Comment by jongfeel** [comment]
> 그리고 왜 sum도 int main(void)에서 int 설정을 해주나요?

그럼 이 질문은 잘못 이해하신 걸까요?

**Comment by park-sohyeon** [comment]
넵 제가 잘못 이해한 것 같습니다.
아래 방식으로 고쳐주었습니다. 아래 방식으로 진행하니 잘 디버깅 되었습니다. 
int sumof(int a, int b) {

	int i, min, max;
	int sum=0;


과 
 int   main(void) { 
 	int a, b;

**Comment by jongfeel** [comment]
다시 고쳐서 디버깅이 잘 되었다는 코드 적어주신 걸 보면
최초에 작성했던 코드와 하나도 다르지 않습니다.

https://github.com/su-hyeok/c_algorithm/blob/07076de9a0d2b7c833e91d86e850a8c8e82ee065/Q9.cpp#L4-L7

https://github.com/su-hyeok/c_algorithm/blob/07076de9a0d2b7c833e91d86e850a8c8e82ee065/Q9.cpp#L24-L25

문제가 어디서 부터 시작된 건지 다시 설명해 주실 수 있을까요?

**Comment by park-sohyeon** [comment]
넵. 따로 고치지 않았습니다.
제가 앞서 고쳤다고 잘못 말했습니다.

이번 문제는 제가 문제를 잘못 이해했던 것 같습니다.

제가 이해를 잘 못했던 부분이  int sumof(int a, int b) 함수에서 int i, min, max; int sum=0; 를 해주고
왜   int main(void) 에서 int a, b; 만 하고 int sum; 을 안해주는지가 궁금하였습니다.

다시 실행해본 결과 int main(void)에 int sum; 을 하지 않아도 잘 실행이 되었습니다. 

그 결과 처음에 제가 작성했던 
int main(void) { 
 	int a, b; 
를 사용하게 되었습니다.

**Comment by jongfeel** [comment]
내용을 보니 local or global 변수의 범위(Variable scope)에 대한 이해 문제였던 것 같습니다.
나중에 한번 논의해 보면 좋을 것 같고요. 미리 아래 링크 참고해 보시면 좋을 것 같습니다.

https://www.w3schools.in/c-tutorial/variable-scope/
