### ISSUE TITLE
practice 2-5, calloc()

### ISSUE THREAD

**Issue by park-sohyeon** [su-hyeok/c_algorithm#6]
height = calloc(number, sizeof(int)); 부분에서 'C++ 형식의 값을 형식의 엔터티에 할당할 수 없습니다.'라는 오류값이 뜹니다. void * 형식의 값을 "int *" 형식의 엔터티에 할당할 수 없다라는 오류.

책에 있는 코드를 그대로 작성하였는데 calloc()에서 자꾸 오류가 나서 디버깅이 안됩니다.

park-sohyeon/exercise 파일 중 2-5.cpp 파일입니다.

**Comment by parkwltn** [comment]
http://www.cplusplus.com/reference/cstdlib/calloc/?kw=calloc

**Comment by jongfeel** [comment]
@zsueue 님이 올려주신 링크의 내용을 보고 어떻게 해결했는지 알 수 있을까요?

**Comment by park-sohyeon** [comment]
height = (int*) calloc(number, sizeof(int)); 로 해결했습니다!!

**Comment by jongfeel** [comment]
https://github.com/su-hyeok/c_algorithm/blob/07076de9a0d2b7c833e91d86e850a8c8e82ee065/2-5.cpp#L22

아직 github에는 변경이 안된 것 같은데 local 파일에서 실행했을 때 잘 됐다는 뜻이죠?

github에도 올려 보면 좋을 것 같습니다.

**Comment by park-sohyeon** [comment]
넵 다시 올렸습니다!!
