### ISSUE TITLE
How about input the title of question contents?

### ISSUE THREAD

**Issue by jongfeel** [su-hyeok/c_algorithm#7]
지금
#4 #5 #6 의 제목이 모두 `질문입니다`로 같은 제목입니다.
이 상황만 보더라도 질문이 있다는 건 알 수 있는데, 어떤 질문인지는 실제 내용을 클릭해 보기 전까지는 모르는 상황입니다.
뭐 3개 까지는 기억을 해 내서 모를리 없겠지만 이런 내용은 수십, 수백개가 쌓이고 한 달, 두 달, 1년이 지난 후에 다시 클릭해서 보려면 상당한 인내심이 필요할지도 모릅니다.

그래서
Title에는 어떤 내용인지에 대한 요약이 있어야 하고요,
클릭하면 구체적인 내용이 있는게 상식적인 수준에서 올바른 글 작성 방법이라고 보여집니다.

유명한 오픈소스인 vscode의 issue 탭을 참고하셔서 어떻게 제목을 만들어서 논의하는지 보면 좋을 것 같습니다.
https://github.com/microsoft/vscode/issues
물론 외국 사람들이라고 질문 제목을 잘 짓는건 아니지만, 적어도 질문(question)이 제목인 issue 글은 없습니다.

**Comment by park-sohyeon** [comment]
네엡!! 제목 수정하였습니다!!
