### ISSUE TITLE
Assignees & Answers

### ISSUE THREAD

**Issue by jongfeel** [su-hyeok/c_algorithm#8]
### Assignees

- Cambridge 영어사전에는 다음과 같은 뜻이 있다고 나와 있습니다
- a person to whom the rights to a property, etc. have been given:
- https://dictionary.cambridge.org/us/dictionary/english/assignee
- 재산의 권리를 부여받은 사람 정도로 나오죠
- 즉, assignees를 할당해 준다는 건, issue 내용에 대해 반드시 확인을 하고 대답, 의견, 논의 등을 하고 싶은 사람으로 지정해 줘야 합니다.
- 물론, assignee로 할당되지 않더라도 자유롭게 대답, 의견, 논의를 할 수 있지만 issue를 제기한 사람이 되도록이면 자신이 할당한 assignee와 논의를 진행해야 합니다.

### Answers

- 대답은 꼭 정답을 얘기해야 하는게 아닐 수 있습니다.
- 충분히 서로간의 이해 관계를 논의하고 역으로 질문하거나 서로 맞다고 생각하는 방향으로 계속해서 얘기해 나가는 과정도 중요합니다.
- assignees가 여려명이지만 누군가 대답 혹은 의견을 냈다고 해도 다른 assignee 역시 본인의 의견을 내야 합니다.
- 만약 이런 과정이 불편하거나 불필요하다면 issue를 제기한 사람은 매우 신중하게 assignee를 설정해야 합니다.

규칙이 엄격하다고 생각하실 수 있지만 issue를 제기하기 전 불필요한 혹은 별 의미 없는 assignee 할당은 주의해야 합니다.

**Comment by parkwltn** [comment]
Assignees 할당을 확인해주세요~의 의미로 알고 사용했는데, 앞으로 주의하겠습니다!
